name: obd
description: A new Flutter project.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  accordion: ^2.5.1
  show_up_animation: ^2.0.0

  # UI
  cupertino_icons: ^1.0.2
  responsive_framework: ^1.0.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.5
  syncfusion_flutter_gauges: ^21.2.4
  syncfusion_flutter_charts: ^21.2.4
  flutter_rating_bar: ^4.0.1
  flutter_easyloading: ^3.0.5
  dropdown_search: ^5.0.6
  modal_bottom_sheet: ^3.0.0-pre
  grouped_list: ^5.1.2

  #location
  geolocator: ^9.0.2

  # Routing
  auto_route: ^7.1.0

  # API
  dio: ^5.1.2
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  dartz: ^0.10.1

  # State Management
  flutter_riverpod: ^2.3.6

  # tools
  url_launcher: ^6.1.11
  intl: ^0.18.1

  # obd
  odb_connect: ^2.0.2
  bluetooth_obd: ^0.0.6
  permission_handler: ^10.2.0
  device_info_plus: ^9.0.0

  # data
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint:
  riverpod_lint:

  flutter_lints: ^2.0.0

  build_runner: ^2.4.4
  json_serializable: ^6.6.2
  auto_route_generator: ^7.0.0

  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.1.0


flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-RegularExpanded.otf
          weight: 400
        - asset: assets/fonts/Exo2-BoldExpanded.otf
          weight: 700