name: flutter_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  equatable: ^2.0.3
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  flutter:
    sdk: flutter
  formz: ^0.4.0
  user_repository:
    path: packages/user_repository
  syncfusion_flutter_gauges: ^20.2.50
  flutter_svg: ^1.1.5
  accordion: ^2.5.1
  url_launcher: ^6.1.6
  show_up_animation: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
dev_dependencies:
  bloc_test:
    path: ./bloc_test
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: English
      fonts:
        - asset: assets/fonts/English-Regular.otf
    